<?php

namespace Iboved\AdvertBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RubricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubricRepository extends EntityRepository
{
    public function getNameRubric()
    {
        return $this->getEntityManager()
            ->getRepository('IbovedAdvertBundle:Rubric')
            ->createQueryBuilder('r')
            ->select('r.name')
            ->getQuery()
            ->getResult();
    }
}
